name: Nightly

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
    inputs:
      force:
        description: "Force build even if commit was already cached"
        required: false
        default: false
        type: boolean

concurrency:
  group: nightly-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  nightly:
    name: Nightly Flatpak Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Check Commit Cache
        id: check-cache
        if: ${{ !(inputs.force) }}
        uses: actions/cache@v6
        with:
          path: .nightly-flag
          key: nightly-built-${{ github.sha }}

      - name: Skip If Already Built
        if: ${{ steps.check-cache.outputs.cache-hit == 'true' && !(inputs.force) }}
        run: echo "Commit ${{ github.sha }} has already been built and published for nightly. Skipping."

      - name: Set short git commit SHA
        id: vars
        run: |
          echo "COMMIT_SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV

      - name: Build Nightly Flatpak Bundle
        if: ${{ steps.check-cache.outputs.cache-hit != 'true' || inputs.force }}
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: page.samuelm333.Cartridges.Devel.flatpak
          manifest-path: flatpak/page.samuelm333.Cartridges.Devel.json

      - name: Publish Nightly Release
        if: ${{ steps.check-cache.outputs.cache-hit != 'true' || inputs.force }}
        uses: softprops/action-gh-release@v3
        with:
          name: "Nightly ${{ env.COMMIT_SHORT_SHA }}"
          tag_name: nightly-${{ env.COMMIT_SHORT_SHA }}
          generate_release_notes: true
          files: page.samuelm333.Cartridges.Devel.flatpak
          fail_on_unmatched_files: true
          prerelease: true

      - name: Create Cache Sentinel
        if: ${{ steps.check-cache.outputs.cache-hit != 'true' || inputs.force }}
        run: |
          touch .nightly-flag

      - name: Save Commit Cache
        if: ${{ steps.check-cache.outputs.cache-hit != 'true' || inputs.force }}
        uses: actions/cache/save@v6
        with:
          path: .nightly-flag
          key: nightly-built-${{ github.sha }}
